version: "3.9"

services:
  api:
    build: .
    volumes:
      - ./src/pyback:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8001:80
    restart: always
