name: publish

on:
  push:
    branches:
      - 'master'

permissions:
  packages: write

jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: cd front && npm ci
      - run: cd front && npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: front
          path: front/dist

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/trafficsurfer/api:latest
